### ISSUE TITLE
npm start 01-Login (Samples)

### ISSUE THREAD

**Issue by joelunmsm2003** [auth0-samples/auth0-angularjs2-systemjs-sample#37]
When npm start look this , Help please
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

**Comment by joelunmsm2003** [comment]
I resolved this , thanx =)

**Comment by Dmytro-Kovbasa** [comment]
How did you solve this? I have the same problem

**Comment by joelunmsm2003** [comment]
i replace file package.json start to
 "scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
....
i worked

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-angular-samples) :)
