### ISSUE TITLE
could i use SystemJS import Auth0Lock ?

### ISSUE THREAD

**Issue by geminiyellow** [auth0-samples/auth0-angularjs2-systemjs-sample#45]
i try to use SystemJS to import auth0-lock, but alway got this error:

```
EXCEPTION: Error in :0:0 caused by: Auth0Lock is not defined
```

i knew this sample use `<script src="http://cdn.auth0.com/js/lock/10.7/lock.min.js"></script>` to load the `Auth0Lock`, but is there anybody can tell me how to import it by SystemJS?

**Comment by peterblazejewicz** [comment]
technically you do not have to resolve or require Auth0.lock in SystemJS. Its already loaded via script tag, but your code (TypeScript) will have to use type declaration either in custom `typings.d.ts` definition file or inline in your code, like in sample service:
https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/blob/master/01-Login/app/auth.service.ts#L6

**Comment by geminiyellow** [comment]
@peterblazejewicz thanks you, but if i dont want to use script tag, how to import it ?

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-angular-samples) :)

**Comment by NelsonRothermel** [comment]
@chenkie: In the examples you linked to I only see auth0-lock referenced in the package.json.  I checked several auth.service.ts files and they don't make use of it, just WebAuth which doesn't integrate with your application and does a redirect.  Do you know of any examples with auth0-lock and SystemJS?

**Comment by chenkie** [comment]
@NelsonRothermel the embedded Lock demonstration is in the embedded-lock branch https://github.com/auth0-samples/auth0-angular-samples/tree/embedded-login
