### ISSUE TITLE
02-Custom login - "Login with google" not work

### ISSUE THREAD

**Issue by dunice-kryuchkov** [auth0-samples/auth0-angularjs2-systemjs-sample#48]
Login with credentials work correctly, buy if we push "Login with google" - no token set and we return to home page. 
But when use 01-Login, and auth with "Lock" at same computer and auth.config.ts file -  login with google work.

Upd: public handleAuthentication() not return error, because this.auth0.parseHash((err, authResult) => authResult is undefined. 
In 'err' we see next: 
Object
{ error: "invalid_token"
errorDescription: "Algorithm HS256 is not supported. (Expected algs: [RS256])" }
HS256 is enabled in advanced options by default...

**Comment by chenkie** [comment]
To resolve this you can set the token signing alg for your client to RS256. See here for more: https://auth0.com/docs/libraries/auth0js/migration-guide#switching-from-hs256-to-rs256

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-angular-samples) :)
