### ISSUE TITLE
Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by lcborn4** [auth0-samples/auth0-angularjs2-systemjs-sample#55]
Full error: 
`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. `

I am adding auth0 tio my sails angular web app. I have the output of the login component however when i try to login i get this error. 

Thanks,

**Comment by chenkie** [comment]
This sounds like a CORS issue on your server. Do you have CORS enabled there?

Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-angular-samples) :)

**Comment by khoaTranCarbon8** [comment]
view comment here https://community.auth0.com/answers/13630/view
free localhost must wait for at least one month to enable cors
